<a href="https://colab.research.google.com/github/aansheeagrwal/python-training/blob/main/numpyfile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
sample_list_of_lists=([[1,2,3],[4,5,6],[7,8,9]])
np.array(sample_list_of_lists)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(2,20,3)


array([ 2,  5,  8, 11, 14, 17])

In [7]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
np.linspace(0,5,10) #generate equal distance 10 number between

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(3) #retuurn a 2-D array with ones on the diagonal and zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(4) # it will generate random values uniformally

array([0.26272506, 0.97724811, 0.37628913, 0.65031727])

In [15]:
np.random.rand(4,3)

array([[0.88877796, 0.14493059, 0.50280859],
       [0.65626601, 0.88051701, 0.35181594],
       [0.84924101, 0.68703862, 0.6436059 ],
       [0.32706968, 0.17332428, 0.70757431]])

In [16]:
b=np.random.randn(3,4) #normal distribution around zero
b

array([[ 1.54320555,  1.65901955, -0.466455  , -1.05373097],
       [ 0.47495372, -1.89471724,  0.17039577, -0.68730067],
       [ 1.07889218,  0.41118404, -0.04218744, -0.64885009]])

In [17]:
b.shape

(3, 4)

In [18]:
b.dtype

dtype('float64')

In [19]:
random_arr=np.random.randint(10,50,5)
random_arr

array([26, 26, 30, 15, 40])

In [20]:
random_arr.max()

np.int64(40)

In [21]:
ab=(4,) #it willbe tuple because if we create 1 element tuple
type(ab)

tuple

In [22]:
a=(1) #it is not tuple
type(a)

int

In [23]:
random_arr.argmin()

np.int64(3)

In [24]:
random_arr.argmax()

np.int64(4)

In [25]:
import numpy as np
sample_arr = np.arange(1,11)
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
sample_arr[2]

np.int64(3)

In [27]:
sample_arr[0:4]

array([1, 2, 3, 4])

In [28]:
sample_arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
sample_mat=np.array(([1,2,3],[4,5,6],[6,7,8]))
sample_mat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
sample_mat[0]
#sample_mat[1][1] #double
#sample_mat[1,2] #single
sample_mat[1:2]

array([[4, 5, 6]])

In [31]:
sample_mat[:2,1:]
sample_mat[1,1:]
sample_arr[0:5]

array([1, 2, 3, 4, 5])

In [32]:
sample_arr[0:3] = 400
sample_arr

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [33]:
print(id(sample_arr[0:5]))
slice_of_sample_arr = sample_arr[0:5]
s=slice_of_sample_arr
print(id(slice_of_sample_arr))
print(id(sample_arr))
print(id(s))

133534090341296
133534090341296
133534092095728
133534090341296


In [34]:
slice_of_sample_arr[:]=100
slice_of_sample_arr

array([100, 100, 100, 100, 100])

In [36]:
sample_arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [37]:
sample_arr_copy = sample_arr.copy()
sample_arr_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [38]:
sample_arr_copy[:]=300
sample_arr_copy

array([300, 300, 300, 300, 300, 300, 300, 300, 300, 300])

In [45]:
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
import numpy as np
sample_arr = np.arange(1,11)
sample_arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
boolean_arr=sample_arr>5
print(boolean_arr)
type(boolean_arr)

[False False False False False  True  True  True  True  True]


numpy.ndarray

In [63]:
sample_arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [62]:
sample_arr[sample_arr<5]

array([1, 2, 3, 4])

In [79]:
print(np.add(a,b))
#numpy.subtract(a,b)
#numpy.multiply(a,b)
#numpy.divide(a,b)

[5 7 9]


In [56]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=np.dot(a,100)
b
#c=np.cross(b,a)
#c

implement bubble sort in python

In [74]:
def bubble_sort(arr):
  n = len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
        arr=[64,34,25,12,22,11,90]
        print("Original array:", arr)
        bubble_sort(arr)
        print("Sorted array:", arr)

In [75]:
import numpy as np
# 3D vectors
a = np.array([1,2,3])
b = np.array([4,5,6])
cross_product_3d = np.cross(a,b)
print(f"cross product of 3D vectors: {cross_product_3d}")

cross product of 3D vectors: [-3  6 -3]


In [76]:
# 2D vectors
x = np.array([1,2])
y = np.array([3,4])
cross_product_2d = np.cross(x,y)
print(f"cross product of 2D vectors: {cross_product_2d}")

cross product of 2D vectors: -2


In [77]:
print(a/a)

[1. 1. 1.]


In [78]:
print(1/a)

[1.         0.5        0.33333333]


In [86]:
import numpy as np
coefficient = [12,3,4,5,10]
polynomialExp= np.poly1d(coefficient)
print('type of polynomial=',type(polynomialExp))
print("Polynomial expression is:",polynomialExp)
print(polynomialExp)
x=2
result=polynomialExp(x)
print(result)
print('================================================================')
#coff=numpy.array([12,0,4,0,10]
#poly=numpy.poly1d(coff)
#print(poly)


type of polynomial= <class 'numpy.poly1d'>
Polynomial expression is:     4     3     2
12 x + 3 x + 4 x + 5 x + 10
    4     3     2
12 x + 3 x + 4 x + 5 x + 10
252


In [87]:
import numpy
a=numpy.matrix(((10,20,30,40),(50,60,70,80)))
print("a: \n", a)
b=numpy.transpose(a)
print('transpose of (a): \n', b)

a: 
 [[10 20 30 40]
 [50 60 70 80]]
transpose of (a): 
 [[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [90]:
import numpy
a= numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(2,3,4,5)))
b= numpy.hsplit(a,2)
print('a\n', a)
print('b\n', b)
c=b[0]
d=b[1]
print('c\n', c)
print('d\n', d)
e=numpy.vsplit(c,2)
f=numpy.vsplit(d,2)
print('e\n', e[0])
print('f\n', f[0])



a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [  2   3   4   5]]
b
 [matrix([[ 10,  20],
        [ 50,  60],
        [ 90, 100],
        [  2,   3]]), matrix([[ 30,  40],
        [ 70,  80],
        [110, 120],
        [  4,   5]])]
c
 [[ 10  20]
 [ 50  60]
 [ 90 100]
 [  2   3]]
d
 [[ 30  40]
 [ 70  80]
 [110 120]
 [  4   5]]
e
 [[10 20]
 [50 60]]
f
 [[30 40]
 [70 80]]
